Update instructions to echo to Cloud loaded webpage
acquia/pipelines-examples pull request #13
Opened 2017-03-08 00:45 UTC by kieranacquia

In the UX session we saw that the user should be able to load the ode and see validating content.

2017-03-10 16:56 UTC, unn requested changes

2017-03-10 16:56 UTC, unn commented on tutorial-701/acquia-pipelines.yaml
> +            - echo "Pipelines examples 701. You successfully deployed your build to an ODE" > index.html
If you want this to work, you should remove the touch, and echo to docroot/index.html

2017-03-10 16:57 UTC, unn commented
@kieranacquia Please update your pull request based on the feedback.

2017-03-21 20:18 UTC, bjaspan commented
Duplicates #15, already committed.

2017-03-21 20:19 UTC, bjaspan commented
Oops, #15 merged into this (#13). Now merging this to master.

2017-03-21 20:19 UTC, merged